OBS:
  URL: localhost:4455
  KEY: ADD_YOUR_OWN_KEY_HERE
  BROWSER: ADD_YOUR_OWN_BROWER_SOURCE_HERE
  MEDIA: Media Source
OPEN_AI:
  KEY: ADD_YOUR_OWN_KEY_HERE
  MODEL: tts-1-hd #tts-1 or tts-1-hd
  SPEED: 0.8 #0.25 to 4.0
  VOICE: alloy #alloy, ash, coral, echo, fable, onyx, nova, sage and shimmer

MICROSOFT:
  KEY: ADD_YOUR_OWN_KEY_HERE
  REGION: eastus
  VOICE: th-TH-NiwatNeural #    th-TH-PrempreedaNeural, th-TH-NiwatNeural: Male voice. Another high-quality neural option., th-TH-AcharaNeural, th-TH-PattaraNeural
  SPEED: 0.8

BOT_NOI:
  KEY: ADD_YOUR_OWN_KEY_HERE
  SPEAKER: 8
  VOLUME: 0.8 # 0.0 - 1.0
  SPEED: 0.8 # 0.0 - 1.0
  TYPE_MEDIA: mp3 # do not setting this
  SAVE_FILE: true # do not setting this
  LANGUAGE: th

RESEMBLE:
  KEY: ADD_YOUR_OWN_KEY_HERE
  VOICE_UUID: 55592656
  SAMPLE_RATE:  48000 # do not setting this
  OUTPUT_FORMAT: mp3 # do not setting this
  SPEED: 80%

GOOGLE:
  KEY: ADD_YOUR_OWN_KEY_HERE
  NAME: th-TH-Chirp3-HD-Leda
  SPEAKING_RATE: 1.0 # 0.25 to 4.0
  PITCH: 0.0 # -20.0 to 20.0
  VOLUME_GAIN_DB: 0.0 # -96.0 to 16.0

GENERAL:
  LIMIT: 200
  TIME_LIMIT: 10
  PLAYER: OBS