AI: "RESEMBLE" #CHOSE YOUR TTS APPLICATION (OPEN_AI, BOT_NOI, RESEMBLE)
OPEN_AI:
  KEY: "ADD_YOUR_OWN_KEY_HERE"
  MODEL: "tts-1-hd" #(tts-1, tts-1-hd)
  SPEED: "0.8"
  VOICE: "alloy"
OBS:
  URL: "localhost:4455"
  KEY: "ADD_YOUR_OWN_KEY_HERE"
  BROWSER: "ADD_YOUR_OWN_BROWER_SOURCE_HERE"
  MEDIA: "ADD_YOUR_OWN_MEDIA_SOURCE_HERE"

LIMIT: 300 #LIMIT CHARACTER PER MESSAGE
TIME_LIMIT: 10 #LIMIT SPEECH TIME PER MESSAGE

BOT_NOI:
  KEY: "ADD_YOUR_OWN_KEY_HERE"
  SPEAKER: "8"
  VOLUME: 0.8
  SPEED: 0.8
  TYPE_MEDIA: "mp3"
  SAVE_FILE: true
  LANGUAGE: "th"

RESEMBLE:
  KEY: "ADD_YOUR_OWN_KEY_HERE"
  VOICE_UUID: "55592656"
  SAMPLE_RATE:  48000
  OUTPUT_FORMAT: "mp3"
  SPEED: "80%"