name: Release

on:
  release:
    types: [created]  # Or [published] if you want to trigger after manual publishing

jobs:
  release:
    runs-on: windows-latest  # This is correct for building on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # v3 is fine, but v4 is the latest if you want to update

    - name: Set up release version
      id: set_version
      run: echo "release_version=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      # Removed the leading space before "release_version"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23' # Fine, but 'stable' is an option for flexibility

    - name: Build application
      run: |
        mkdir -p releases
        go build -o releases/Takluz_TTS.exe -ldflags="-s -w" main.go
        cp application/config.yaml releases/

    - name: Zip application folder
      run: |
        Compress-Archive -Path releases/* -DestinationPath Takluz_TTS_${{ env.RELEASE_VERSION }}.zip -Force
      # Case-insensitive, but env.RELEASE_VERSION is more conventional

    - name: Upload Release Asset (ZIP)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Takluz_TTS_${{ env.RELEASE_VERSION }}.zip
        asset_name: Takluz_TTS_${{ env.RELEASE_VERSION }}.zip
        asset_content_type: application/zip