name: Release

on:
  release:
    types: [created]  # Or [published] if you want to trigger after manual publishing

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use v3, it's more current

    - name: Zip Takluz_TTS folder
      run: zip -r Takluz_TTS.zip Takluz_TTS

    - name: Upload Release Asset (ZIP)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for authorization
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Takluz_TTS.zip # Make sure this path is correct!
        asset_name: Takluz_TTS.zip
        asset_content_type: application/zip

