name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_path: ./Takluz_TTS.exe
        asset_name: Takluz_TTS.exe
        asset_content_type: application/octet-stream
    - name: Upload example.yaml
      uses: actions/upload-release-asset@v1
      with:
        asset_path: ./example.yaml
        asset_name: example.yaml
        asset_content_type: text/yaml
