name: Release

on:
  release:
    types: [created]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload Takluz_TTS.exe
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Takluz_TTS.exe
        asset_name: Takluz_TTS.exe
        asset_content_type: application/octet-stream

    - name: Upload example.yaml
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./example.yaml
        asset_name: example.yaml
        asset_content_type: text/yaml