name: Release

on:
  release:
    types: [created]  # Or [published] if you want to trigger after manual publishing

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use v3, it's more current

    - name: Set up release version
      run: echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

    - name: Zip application folder
      run: cd application && zip -r ../Takluz_TTS_${{ env.RELEASE_VERSION }}.zip . && cd ..

    - name: Upload Release Asset (ZIP)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for authorization
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Takluz_TTS_${{ env.RELEASE_VERSION }}.zip # Make sure this path is correct!
        asset_name: Takluz_TTS_${{ env.RELEASE_VERSION }}.zip
        asset_content_type: application/zip

